[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install",
  "cd server && npm install && cd .."
]

[phases.build]
cmds = [
  "npm run build",
  "ls -la",
  "ls -la dist || echo 'dist folder not found'"
]

[start]
cmd = "npm start"
