[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "cd .. && npm install",
  "cd server && npm install"
]

[start]
cmd = "node build-frontend.js && node src/db/migrate.js && node src/index.js"
